language: julia

os:
    - osx
    - linux

julia:
    - 1.0
    - 1
    - nightly
notifications:
    email: false

# only needed on linux for deserialization tests
addons:
  apt:
    packages:
    - libxt6
    - libxrender1
    - libxext6
    - libgl1-mesa-glx
    - libqt5widgets5

script:
    - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
    - if [[ $(julia --version) == *'1.0.'* ]]; then echo 'Overriding project toml' && cp compat/Project.toml Project.toml; fi
    - export JULIA_PROJECT=$(pwd)
    - travis_wait 30 julia --color=yes -e 'using Pkg; Pkg.activate(); Pkg.instantiate(); Pkg.test(coverage=true)';

after_success:
    - julia -e 'using Pkg; cd(Pkg.dir("TensorBoardLogger")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add("Documenter"); Pkg.develop(PackageSpec(path=pwd()));
                                    Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
